### ISSUE TITLE
wrong number of arguments for 'set' command

### ISSUE THREAD

**Issue by kerspoon** [Automattic/kue#603] opened 2015-05-06 15:03 UTC
Using the sample code (below) on version `0.9.1` fails with the error message below. If I install kue version `0.8.12` it all works properly.

```
var kue = require('kue')
 , queue = kue.createQueue();

queue.process('email', function(job, done){
  email(job.data.to, done);
});

function email(address, done) {
  if(!isValidEmail(address)) {
    //done('invalid to address') is possible but discouraged
    return done(new Error('invalid to address'));
  }
  // email send stuff...
  done();
}
```

```
fiveapp@brooks:~/dashboard/pdfKue$ node .

/home/fiveapp/dashboard/pdfKue/node_modules/kue/node_modules/redis/index.js:575
                throw callback_err;
                      ^
Error: ERR wrong number of arguments for 'set' command
    at ReplyParser.<anonymous> (/home/fiveapp/dashboard/pdfKue/node_modules/kue/node_modules/redis/index.js:317:31)
    at ReplyParser.emit (events.js:95:17)
    at ReplyParser.send_error (/home/fiveapp/dashboard/pdfKue/node_modules/kue/node_modules/redis/lib/parser/javascript.js:296:10)
    at ReplyParser.execute (/home/fiveapp/dashboard/pdfKue/node_modules/kue/node_modules/redis/lib/parser/javascript.js:181:22)
    at RedisClient.on_data (/home/fiveapp/dashboard/pdfKue/node_modules/kue/node_modules/redis/index.js:547:27)
    at Socket.<anonymous> (/home/fiveapp/dashboard/pdfKue/node_modules/kue/node_modules/redis/index.js:102:14)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
```

**Comment by behrad** [comment] 2015-05-06 18:00
the above code is OK

**Comment by epicbagel** [comment] 2015-05-26 21:57
Also getting this error since upgrading, looks to be related to the redis package itself (redis/index.js:575)?

**Comment by behrad** [comment] 2015-05-27 06:06
provide me the code, or case generating this please :)

**Comment by alexkavon** [comment] 2015-06-16 17:58
@kerspoon Did you find a solution to this?

**Comment by elad** [comment] 2015-06-28 08:51
You might be using an old redis version. For me, upgrading to 3.0 fixed it.

**Comment by behrad** [comment] 2015-06-28 12:19
@alexkavon whats your redis/kue/node versions?

**Comment by alexkavon** [comment] 2015-06-28 18:57
It is indeed caused by an old version of redis. I think this issue can be closed.

**Comment by behrad** [comment] 2015-06-28 19:15
thank you @alexkavon

**Comment by UnbrandedTech** [comment] 2015-07-21 07:03
The requirements need to change on the READ.me if 3.0 is required

**Comment by elad** [comment] 2015-07-21 07:08
I just submitted a pull request in case this is of interest to the maintainers. :)

**Comment by behrad** [comment] 2015-07-21 09:16
I'm using kue on redis 2.8
redis 3.0 is an strict requirement, many redis instaces are still 2.8 or late 2.6
We should first resolve this.

**Comment by behrad** [comment] 2015-07-21 09:17
this should be an incompatibility between `node_redis` and `redis` versions.

**Comment by elad** [comment] 2015-07-23 16:57
@behrad I agree, so let's first reopen this issue. :)

**Comment by singhketan** [comment] 2015-08-13 01:08
Any solutions yet? I'm on windows now, and we've only got port for 2.8 I suppose. What should I do?

**Comment by behrad** [comment] 2015-08-13 06:30
I don't believe this is an issue with Kue @singhketan unless some body facing this, could clarify otherwise.
So, this should be a conflict between node_redis and Redis version of yours. Can you claim that exactly on which version of redis is this causing for you? Can you test with another version of Redis? or even another version of node_redis with manually npm installing that module inside kue?

**Comment by joshbedo** [comment] 2015-08-15 17:03
I feel like 
```
Redis >= 2.6.12
```
should say `Redis = 3.0` if this is the case, i'm experiencing the same problem on windows with 2.8 which should be compatible according to the readme.

**Comment by behrad** [comment] 2015-08-15 17:29
I have successful deployments of kue is currently on redis 2.8, of course on Ubuntu and CentOS

**Comment by joshbedo** [comment] 2015-08-16 13:19
i ended up spinning up an Ec2 redis instance with docker to work around the Windows port bugs in 2.8.

**Comment by behrad** [comment] 2015-08-16 14:37
So your OK now, I think we should close this, since this directly relates to redis & its node drivers.

**Closed by behrad** 2015-08-16 14:37 UTC
Labels: need more info

**Comment by ikbelkirasan** [comment] 2017-09-29 21:47
I had this issue with Redis 2.4.6 on Windows. Updated to 3.0.501 and the problem was solved.
