### ISSUE TITLE
[RedisLabs Users] Lots of Inactive Jobs

### ISSUE THREAD

**Issue by jjchando** [Automattic/kue#815] opened 2016-01-27 18:48 UTC
Hello - we have Kue running on an ElasticBeanstalk on AWS and connected to a 500MB Redis instance on Rediscloud - webservers are connected from Heroku. It's set up with Redis Version Compliance 3.0.3. 

Here's how I have the connection set up.
```
jobs = kue.createQueue({
	redis:
		port: 18147
		host: "XXX.us-east-1-4.1.ec2.garantiadata.com"
		auth: "MyPassword"
	})
```
When I first deployed it, kue was processing the jobs perfectly. However, since deploying this we are seeing lots of jobs not even get processed and go right to inactive. They haven't even been attempted to be processed. I looked at the other issues about inactive jobs but none seem to have applied. Does anyone know why these jobs are going direct to inactive and not failed/delayed? Let me know if I can provide any more information. Thanks

**Comment by jjchando** [comment] 2016-01-27 23:37
How does one manually move inactive jobs to be active again?

**Comment by behrad** [comment] 2016-01-28 09:48
Does calling `watchStuckJobs` save you from this?

**Comment by peterporfy-planorama** [comment] 2016-02-01 14:07
Hey, we experienced the very same issue today with EB and a 500 Mb Redis instance from the same provider. We had 20 as processing concurrency for each job (they are very similar) and every time I restarted the EB service it could get processed about 20 then stopped. Meanwhile new jobs were running seamlessly. I could not solve it with the other github threads (I have everything in place from watchStuck and domains and everything was working fine until the production instance). Once I decreased the processing concurrency to 1 from 20 it could process all of them and no problem since that. I would like to increase this since the jobs are very i/o heavy so it can run concurrently. One more possible interesting detail is that all the stuck jobs were the same type. It might be a coincidence but I don't know.

**Comment by peterporfy-planorama** [comment] 2016-02-02 08:11
We also tried with another service and with 5x concurrency and the same happened. After setting the concurrency to 1 it worked nicely. There is also only type of task being stucked so I will try to find something common in the two (it might be only that those types are more frequently created).

**Comment by peterporfy-planorama** [comment] 2016-02-02 15:42
It boiled down to be a problem in the Worker module at the getJob function when it calls blpop. For some reason with RedisLabs when you do multiple blpop for a key from the same node process. 

I don't know why is it happening because I don't know the redis blpop internals (it was the same with multiple node redis clients). After reading what blpop is it was a bit strange for me that all the separate workers are doing it simultaneously and the only working setup for me is concurrency:1 which is only 1 blpop/type. 

To temporary come over this situation I made a monkey patch for Worker.getJob which does not allow multiple blpop/type. It queues up the getJob calls in a js array and pops the next after blpop returns. It is pretty straightforward and reasonable but I think about it as a temporary solution. It now works with many concurrent processor function (I did a test with RedisLabs, concurrency:50, 2 types and 2 node servers with about 40k jobs). I would need to get more deeper into how blpop works and why is it only happening with certain providers.

If any of you need more info or you have something to add lets keep up the discussion about this stuck problem.

**Comment by behrad** [comment] 2016-02-02 18:57
Nice details @peterporfy-planorama , Can you show me your changed worker getJob snippet?

Have you contacted RedisLabs guys for this? their blpop implementation may be different than default redis. Are you sure your old code was running OK with another redis instance except RedisLabs?

**Comment by jjchando** [comment] 2016-02-02 20:33
@peterporfy-planorama +1 would also love to see the snippet.

**Comment by peterporfy** [comment] 2016-02-03 09:36
I wrote a script yesterday to easily reproduce the issue:

`var kue = require('kue');

//require('./blpop-fix');

var queue = kue.createQueue({
  prefix: '_test2'
});

function create(type) {
  queue.create(type, {}).removeOnComplete(true).save();
}

var concurrency = 2;
var timeout = 2000;
queue.process('test', concurrency, function(job, done) {
  setTimeout(done, timeout);
});
queue.process('foo', concurrency, function(job, done) {
  setTimeout(done, timeout);
});

var max = 10;
var current = 0;
function creator() {
  setTimeout(function() {
    create('test');
    create('foo');
    if (++current <= max) {
      creator();
    }
  }, 500);
}
creator();

kue.app.listen(1337);
`

So basically if I create jobs more frequently than a single processor can consume it then it is going to stuck. If the processors would be faster than the creator then there would be no problem (so it _might_ be not that more Workers are waiting for BLPOP but when multiple BLPOP results should be returned for more than one Worker). If I use a local redis (3.0.6) there is no problem. If I use RedisLabs we run to this issue very fast.

If I apply the patch by removing comments from `//require('./blpop-fix');` it works with RedisLabs.

blpop-fix:

```var Worker = require('kue/lib/queue/worker');
var Job = require('kue/lib/queue/job');
var redis = require('kue/lib/redis');

var ongoing_blpop = {};
var blpop_queue = [];

// this is the replication of a local module scope clients variable within
// the original Worker. getJob and shutdown uses it.
var clients = {};

/**
 * This is a monkey patch for Kue version 0.10.5.
 *
 * For some reason multiple workers (e.g. queue.process('type', n) where n > 1)
 * get stucked with blpop if they don't wait for each other.
 *
 * This only happens within the same node process.
 *
 * This does not happen for every redis server. We experienced it with RedisLabs.
 *
 *
 * Hack point 1:
 * 	If a BLPOP is ongoing skip the current function call and put it in a queue for later
 * 	usage.
 *
 * Hack point 2:
 *  1. Delete the flag so next getJob call can run without problem.
 *  2. If we have a waiting getJob call in the queue we can use that to process the next job.
 */
Worker.prototype.getJob = function( fn ) {
  var self = this;
  if( !self.running ) {
    return fn("Already Shutdown");
  }
  // alloc a client for this job type
  var client = clients[ self.type ] || (clients[ self.type ] = redis.createClient());

  // hack point 1
  if (ongoing_blpop[self.type]) {
    return blpop_queue.push(function() {
      self.getJob(fn);
    });
  } else {
    ongoing_blpop[self.type] = true;
  }

  // BLPOP indicates we have a new inactive job to process
  client.blpop(client.getKey(self.type + ':jobs'), 0, function( err ) {

    // hack point 2
    delete ongoing_blpop[self.type];
    var next = blpop_queue.shift();
    if (next) process.nextTick(next);

    if( err || !self.running ) {
      self.client.lpush(self.client.getKey(self.type + ':jobs'), 1);
      return fn(err);		// SAE: Added to avoid crashing redis on zpop
    }
    // Set job to a temp value so shutdown() knows to wait
    self.job = true;
    self.zpop(self.client.getKey('jobs:' + self.type + ':inactive'), function( err, id ) {
      if( err || !id ) {
        self.idle();
        return fn(err /*|| "No job to pop!"*/);
      }
      Job.get(id, fn);
    });
  });
};

/**
 * NOTE
 * We only have to put it here because it uses the clients object which is local to this
 * monkey patch module
 */
Worker.prototype.shutdown = function( timeout, fn ) {
  var self = this, shutdownTimer = null;
  if( arguments.length === 1 ) {
    fn      = timeout;
    timeout = null;
  }

  // Wrap `fn` so we don't pass `job` to it
  var _fn = function( job ) {
    if( job && self.job && job.id != self.job.id ) {
      return; // simply ignore older job events currently being received until the right one comes...
    }
    shutdownTimer && clearTimeout(shutdownTimer);
    self.removeAllListeners();
    self.job        = null;
    //Safeyly kill any blpop's that are waiting.
    (self.type in clients) && clients[ self.type ].quit();
    delete clients[ self.type ];
    self.cleaned_up = true;
    //fix half-blob job fetches if any
    self.client.lpush(self.client.getKey(self.type + ':jobs'), 1, fn);
  };

  if( !this.running ) return _fn();
  this.running = false;

  // As soon as we're free, signal that we're done
  if( !this.job ) {
    return _fn();
  }
  this.on('idle', _fn);
  this.on('job complete', _fn);
  this.on('job failed', _fn);
  this.on('job failed attempt', _fn);

  if( timeout ) {
    shutdownTimer = setTimeout(function() {
      // shutdown timeout reached...
      if( self.job ) {
        self.drop_user_callbacks = true;
        self.removeAllListeners();
        if( self.job === true ) {
          self.once('idle', _fn);
        } else {
          // a job is running, fail it and call _fn when failed
          self.once('job failed', _fn);
          self.once('job failed attempt', _fn);
          self.failed(self.job, { error: true, message: "Shutdown" });
        }
      } else {
        // no job running, just finish immediately
        _fn();
      }
    }.bind(this), timeout);
  }
};
```

Note that we are going to test this on staging. It works well on local development machine but if you could review or @jjchando could test it with their system too that would be great.

I didn't contact with RedisLabs yet but I will.

**Comment by behrad** [comment] 2016-02-03 10:29
great. I will definitely check this out to see if I can reproduce it on my side.

**Comment by peterporfy** [comment] 2016-02-03 10:59
A more stripped down test:
```javascript

var redis = require('redis');
var _ = require('lodash');

function createClient() {
  return redis.createClient( );
}

var client = createClient();
var client2 = createClient();

var key = '_test2:direct_test';

function blpop() {
  client.blpop(key, 0, function(err, result) {
    if (err) return console.error(err);
    console.log(result[1]);
    blpop();
  });
}

function lpush(number) {
  client2.lpush(key, number);
}

client.del(key, function(err) {
  if (err) return console.error(err);
  _.times(2, blpop);
  _.range(0, 10).forEach(lpush);
});

```

**Comment by peterporfy-planorama** [comment] 2016-02-04 08:23
I wrote to RedisLabs support and they managed to reproduce the issue. They are working on a solution. I will keep you updated.

**Comment by pepoviola** [comment] 2016-02-05 02:22
:+1:  @peterporfy-planorama great news, I catch this error to in #772 using redislabs ( in my case the errors starts after they made some infrastructure upgrade ).

Thx!

**Comment by lindo-jmm** [comment] 2016-02-05 16:40
@ghost Thanks for keeping us updated!

**Comment by peterporfy** [comment] 2016-02-10 12:09
No result yet but we successfully processed over 200k jobs (with 5 as concurrency) with the patch above on production.

**Comment by jurgen7777** [comment] 2016-03-04 23:58
We have the same issue with stuck jobs on Heroku with Redis Cloud in production.
@peterporfy Thanks for the script for reproducing an issue.

I used a "monitor" Redis command. And it seems that if redis client issues two or more "blpop" commands **using the same connection**, they stuck. Same as in the @peterporfy test

```javascript
_.times(2, blpop);
```

I don't know what is the reason for that, and is that a normal behavior, but it might because of two or more "blocking" blpops "hanging" on the one redis client connection). (And it really not being reproduced on the local machine)

In my case I used concurrency 15, there are 15 workers created. But I noticed that all of them used the same connection, created once. Here is monitor output, note the same port 56813

```bash
1457131330.815332 [0 93.85.50.33:56813] "blpop" "q:foo:jobs" "0"
1457131330.815514 [0 93.85.50.33:56813] "blpop" "q:foo:jobs" "0"
1457131330.815729 [0 93.85.50.33:56813] "blpop" "q:foo:jobs" "0"
1457131330.815944 [0 93.85.50.33:56813] "blpop" "q:foo:jobs" "0"
1457131330.816157 [0 93.85.50.33:56813] "blpop" "q:foo:jobs" "0"
1457131330.816493 [0 93.85.50.33:56813] "blpop" "q:foo:jobs" "0"
1457131330.816700 [0 93.85.50.33:56813] "blpop" "q:foo:jobs" "0"
1457131330.816922 [0 93.85.50.33:56813] "blpop" "q:foo:jobs" "0"
1457131330.817233 [0 93.85.50.33:56813] "blpop" "q:foo:jobs" "0"
```

Here is a small fix 888fa1be76d421db25c40a08652d550d15df5d73, that lets it create a new redis client connection for each worker, and make worker instance use them.
Note the different client ports.

```bash
1457132051.504506 [0 93.85.50.33:2227] "blpop" "q:foo:jobs" "0"
1457132051.506427 [0 93.85.50.33:45498] "blpop" "q:foo:jobs" "0"
1457132051.885138 [0 93.85.50.33:53090] "blpop" "q:foo:jobs" "0"
1457132051.911360 [0 93.85.50.33:23292] "blpop" "q:foo:jobs" "0"
1457132051.943164 [0 93.85.50.33:12361] "blpop" "q:foo:jobs" "0"
1457132052.085304 [0 93.85.50.33:46174] "blpop" "q:foo:jobs" "0"
1457132052.085304 [0 93.85.50.33:46174] "blpop" "q:foo:jobs" "0"
```

I checked that on a 10000 jobs, seems to be ok.
Thanks.

**Comment by behrad** [comment] 2016-03-05 06:32
Great effort @jurgen7777 , but are you sure it is the same connection doing two blpops? I mean when a connection is blocking on a blpop, how can the second one be made?

**Comment by jurgen7777** [comment] 2016-03-05 06:59
Yes, I'm sure, It easily can be checked by the code, provided by @peterporfy 

```javascript
function blpop() {
  client.blpop(key, 0, function(err, result) {
    if (err) return console.error(err);
    console.log(result[1]);
    blpop();
  });
}
```
Calling this function twice, makes two "blpop" commands to go into Redis from the same client connection. Then the problems start.

The blpop commands can be seen 
```bash
redis-cli monitor | grep blpop
```

**Comment by deepakmani** [comment] 2016-03-09 07:56
Hi @jurgen7777 and @behrad

Just wondering if you see any relation to the number of blocked clients with "Inactive Jobs": 

I have a test server using REDIS Cloud on heroku and recently all jobs were going to the "Inactive State"

Here is the output of INFO:
connected_clients:16
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:13

The number of connected clients goes to 23 when using it.

Does concurrency have anything to do with your issue?


Here is the code:

```
// Serverside Controller
var job = queue.create('findEmail', {
			   						name:  					name,
			   						domain: 				domain,
			   						linkedin_profile_url: 	linkedin_profile_url,
			   						twitter_handle: 		twitter_handle,
			   						username: 				req.user.username
			   					})

        			 .ttl(120000) // Timeout for completion - 2  minutes
        			 .attempts(2) // Number of attempts
        			 .priority("high")
        			// .removeOnComplete(true) // Remove job from redis if not failed or processing
        			 .save( function(err){
		  				 if( !err ) console.log( job.id );
		  				 res.send(200, job.id);
					});
```
```
// Worker from procfile
var kue_obj = kue.createQueue({
                prefix: 'q',
                redis: redis
              });

	kue_obj.process('findEmail', 20, function(job, done){

		console.log("Nemam Amma Bhagavan Sharanam -- Trying to process job");
  		find_email(job, done);
	});
```

**Comment by jurgen7777** [comment] 2016-03-09 09:18
@deepakmani @behrad As per the kue source - concurrency - is the number of workers created.
```javascript
/**
 * Process jobs with the given `type`, invoking `fn(job)`.
 *
 * @param {String} type
 * @param {Number|Function} n
 * @param {Function} fn
 * @api public
 */

Queue.prototype.process = function( type, n, fn ) {
  var self = this;

  if( 'function' == typeof n ) fn = n, n = 1;

  while( n-- ) {
    var worker = new Worker(this, type).start(fn);
    worker.id  = [ self.id, type, self.workers.length + 1 ].join(':');
    worker.on('error', function( err ) {
      self.emit('error', err);
    });
    worker.on('job complete', function( job ) {
      // guard against emit after shutdown
      if( self.client ) {
        self.client.incrby(self.client.getKey('stats:work-time'), job.duration);
      }
    });
    // Save worker so we can access it later
    self.workers.push(worker);
  }
  this.setupTimers();
};
```

Thus if you have specified concurrency=20, you should have at least 20 client connections created for each worker. But in reality it seems that client connection is "cached" and all workers reuse the same connection. This leads to execution of "blpop" blocking many times within one connection, and everything is stuck. At the same time if you use concurrency=1, only one worker is created, one connection for this worker and it seems all is fine ( as stated by @ghost post):

> Once I decreased the processing concurrency to 1 from 20 it could process all of them and no problem since that

**Comment by behrad** [comment] 2016-03-09 11:20
> But in reality it seems that client connection is "cached" and all workers reuse the same connection

How is this happening @jurgen7777 Have you any clue about the redis connection caching?

**Comment by jurgen7777** [comment] 2016-03-09 11:35
In the Worker constructor function, the line:
```javascript
this.client  = Worker.client || (Worker.client = redis.createClient());
```
it checks if there is already a connection created, if not it creates it. Thus if you have concurrency=20, worker constructor is called 20 times, but redis.createClient() is called once.


here is the full constructor source code:
```javascript
function Worker( queue, type ) {
    this.queue   = queue;
    this.type    = type;
    this.client  = Worker.client || (Worker.client = redis.createClient());
    this.running = true;
    this.job     = null;
  }
```

**Comment by behrad** [comment] 2016-03-09 11:36
Thank you @jurgen7777 , Does this (https://github.com/Automattic/kue/pull/844) solve your issues guys?

**Comment by peterporfy** [comment] 2016-03-17 16:56
I think it solves the issue but I am a bit concerned about opening a connection for each worker. Mainly for the same reason @behrad said in https://github.com/Automattic/kue/pull/844. Isn't it better to create only one connection per job type? This is what we do know in production (over 2 million jobs processed) with my patch above.

**Comment by behrad** [comment] 2016-03-17 19:40
I'm not convinced how #844 is supposed to work? and remember that `this.client` is not being used for BLPOP, but also for each job type we store a connection inside `clients`.

**Comment by jurgen7777** [comment] 2016-03-17 20:26
@behrad I'm not going to convince you :) I don't insist that changing few lines will make the library perfect. This is just a quickfix of a problem.

>  and remember that this.client is not being used for BLPOP
this is the part of my change. (you can check the changeset)

> but also for each job type we store a connection inside clients.
do you mean this part:
```javascript
var client = clients[ self.type ] || (clients[ self.type ] = redis.createClient());
```
If yes, then this is the place where you have 1 connection per type. If concurrency>1 this one connection is used to call blpop as many times as concurrency value set. Here is the place where processing starts to stuck (on cloud services only).

@peterporfy 
> Isn't it better to create only one connection per job type

Probably it's better, but will it work if there are 2 or more processes running the queue? For instance how many workers do you have in production for jobs processing? I wonder how this ```var ongoing_blpop = {};``` and ```var blpop_queue = [];``` will be synchronized between 2 different processes..?

**Comment by peterporfy** [comment] 2016-03-18 09:32
@jurgen7777 I don't synchronize between processes but a different process will have a different connection and so the `blpop` issue won't affect it. It is only to ensure that one connection is doing one `blpop`. Pretty much the same what you did in your PR. I tested it with 3-4 node processes with the test above. Btw @ghost is me too here I just merged my accounts. :)

**Comment by jurgen7777** [comment] 2016-03-18 09:42
@peterporfy Thanks, for explanation. For me you patch looks nicer.

**Comment by deepakmani** [comment] 2016-03-30 12:43
Hello,
As someone who doesn't have the indepth understanding of Redis, our team decided to switch to Heroku Redis service. 
It seemed to be more reliable than Redis Cloud for 3 weeks :). 
Today on a one test server the jobs keep going into the inactive state and randomly getting worked on after a while. 
Live server is fine for now but its concerning that Redis provider are not that reliable.
I tried restarting the heroku worker,  deleting connections and added the monkey patch which peterporfy shared earlier. 

@peterporfy does the patch work if jobs are already in inactive state? 
Can someone please point me in the right direction?

**Comment by deepakmani** [comment] 2016-03-30 13:04
Hello,
We decided to evaluate Heroku Redis to see if it was better than Redis Cloud and was good for 3 weeks :)
Now on one of our test servers jobs appear to be going into inactive state and after sometime randomly getting processed (checked using Kue UI).
I tried killing Redis connections, restarting the heroku worker, and applied the monkey patch which peterporfy shared. 
@peterporfy Will the monkey patch work on Heroku Redis and if already there are inactive jobs? 

Can someone please point me in the right direction?
Thanks.

**Comment by jurgen7777** [comment] 2016-03-30 13:28
@deepakmani @peterporfy Monkey patch should work on inactive jobs as well

**Comment by deepakmani** [comment] 2016-03-30 14:33
Thanks @jurgen777. 
Based on the comments it sounded like it was an issue caused by Redis Cloud infrastructure upgrade.
After swapping another Heroku redis the jobs are running, but the patch doesnt help with the affected redis instance. 

Seems like it may not be isolated to Redis Cloud 
Can you advise based on this output from redis-cli monitor:

```
OK
1459348273.067230 [0 10.41.201.49:59728] "set" "promotion:lock" "DbK2QPaEEeWxMfW7U/jJLQ==" "PX" "2000" "NX"
1459348273.067317 [0 10.41.201.49:59728] "set" "activeJobsTTL:lock" "DbK2QfaEEeWxMfW7U/jJLQ==" "PX" "2000" "NX"
1459348273.068303 [0 10.41.201.49:59724] "zrangebyscore" "q:jobs:delayed" "0" "1459348273061" "LIMIT" "0" "1000"
1459348273.068461 [0 10.41.201.49:59724] "zrangebyscore" "q:jobs:active" "100000" "1459348273061" "LIMIT" "0" "1000"
1459348273.069376 [0 10.41.201.49:59728] "evalsha" "8797e0a1d8a2721e3b17f21ae1236166a81be165" "1" "promotion:lock" "DbK2QPaEEeWxMfW7U/jJLQ=="
1459348273.069401 [0 lua] "get" "promotion:lock"
1459348273.069408 [0 lua] "del" "promotion:lock"
1459348273.069524 [0 10.41.201.49:59728] "evalsha" "8797e0a1d8a2721e3b17f21ae1236166a81be165" "1" "activeJobsTTL:lock" "DbK2QfaEEeWxMfW7U/jJLQ=="
1459348273.069541 [0 lua] "get" "activeJobsTTL:lock"
1459348273.069546 [0 lua] "del" "activeJobsTTL:lock"
1459348274.068556 [0 10.41.201.49:59728] "set" "promotion:lock" "Dktz0PaEEeWxMfW7U/jJLQ==" "PX" "2000" "NX"
1459348274.068778 [0 10.41.201.49:59728] "set" "activeJobsTTL:lock" "Dktz0faEEeWxMfW7U/jJLQ==" "PX" "2000" "NX"
1459348274.069632 [0 10.41.201.49:59724] "zrangebyscore" "q:jobs:delayed" "0" "1459348274062" "LIMIT" "0" "1000"
1459348274.069871 [0 10.41.201.49:59724] "zrangebyscore" "q:jobs:active" "100000" "1459348274062" "LIMIT" "0" "1000"
1459348274.071089 [0 10.41.201.49:59728] "evalsha" "8797e0a1d8a2721e3b17f21ae1236166a81be165" "1" "promotion:lock" "Dktz0PaEEeWxMfW7U/jJLQ=="
1459348274.071110 [0 lua] "get" "promotion:lock"
1459348274.071116 [0 lua] "del" "promotion:lock"
1459348274.071343 [0 10.41.201.49:59728] "evalsha" "8797e0a1d8a2721e3b17f21ae1236166a81be165" "1" "activeJobsTTL:lock" "Dktz0faEEeWxMfW7U/jJLQ=="
```

**Comment by behrad** [comment] 2016-04-02 08:47
Shall we close this guys?

**Comment by deepakmani** [comment] 2016-04-02 11:05
It would be good to qualify this as a Redis Cloud issue since and  identify
what is causing it to behave like this. Otherwise if it's common, then does
it need a PR?

Thanks.
On Apr 2, 2016 2:17 PM, "Behrad" <notifications@github.com> wrote:

Shall we close this guys?

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/Automattic/kue/issues/815#issuecomment-204675576>

**Comment by behrad** [comment] 2016-04-02 11:44
I interpret this as an issue only with Redislabs users, and I don't think creating a separate BLPOP connection is a good idea.

**Comment by peterporfy** [comment] 2016-04-07 13:12
@behrad I just got an update from RedisLabs and I am going to test their fix. Probably early next week because I am very busy at the moment.

**Comment by peterporfy** [comment] 2016-04-11 09:45
My tests are passing on RedisLabs so they successfully resolved the issue. I think we can close this thread now. I won't open a pull request with my patch and will start to remove it from our systems. If I see any issues I will update you.

**Comment by behrad** [comment] 2016-04-11 10:09
Thank you for your update @peterporfy

**Closed by behrad** 2016-04-11 10:09 UTC

**Comment by sharath91** [comment] 2016-08-01 10:15
@peterporfy We've been facing this issue. Is this issue fixed in redis version 3.2.1?

**Comment by dexwiz** [comment] 2017-07-08 00:05
I am experiencing this issue with Heroku Redis Private instances. Is this still a problem?

**Comment by tomandersen** [comment] 2018-02-07 21:29
We had this issue with a kue on Heroku running about 10,000 events per day with RedisCloud we had delayed and other events going to inactive for up to 30 mins. It was fixed for us by adding watchStuckJobs() right after we created the Queue. It would be nice to see this bug fixed!
