### ISSUE TITLE
Jobs are not in order or not shown in order when displayed in the UI

### ISSUE THREAD

**Issue by Techwraith** [Automattic/kue#33] opened 2011-07-07 23:10 UTC
See what I mean here: http://twitpic.com/5mpuqo

Looks like it's being shown in alpha order instead of numerical.

**Comment by dweinstein** [comment] 2015-02-18 02:33
getting sorted to work right on the UI would be awesome :+1:

**Comment by behrad** [comment] 2015-02-18 07:56
the sorting issue is not related to UI and is builtin in regard with how Redis sorting works. Please read linked issues above in detail...
This will be fixed in later versions

**Comment by invernizzie** [comment] 2015-03-05 18:32
The fact that this bug is still open means kue does not actually behave as a priority queue?
I'd appreciate if someone would let me know before I actually try it, and save me some precious time.

This sounds weird, however, since kue is avertised as a "priority job queue"...

**Comment by dweinstein** [comment] 2015-03-05 22:48
The problem isn't in the job queue or the priority of those jobs, but in the display of the jobs in a web based UI. Often the jobs are not *displayed* in a sorted (numeric) order, which has been an annoyance for using kue at least for me.

**Comment by behrad** [comment] 2015-03-06 00:10
this is sure a bug within kue, the source is how redis behaves on Sorted Set key collations, However this wont affect the prioritization of jobs, but sorting them.
This will be solved in future minor version bump.

**Comment by invernizzie** [comment] 2015-03-06 12:08
Thanks for the clarification.

**Comment by behrad** [comment] 2015-03-06 13:02
and this happens just for job ids when most significant digit is moved forward

1
10
100
1000
...

**Comment by behrad** [comment] 2015-03-22 21:56
this is moved to 1.0.0

**Comment by behrad** [comment] 2015-07-30 07:32
https://github.com/Automattic/kue/issues/678

**Comment by behrad** [comment] 2015-11-20 19:20
Fixed in 0.10.3

**Closed by behrad** 2015-11-20 19:20 UTC
Labels: Bug, Optimization
