### ISSUE TITLE
automatic fail after x seconds?

### ISSUE THREAD

**Issue by gebrits** [Automattic/kue#555] opened 2015-03-30 08:57 UTC
Is it possible to have a job fail automatically after x seconds passed since job was pulled from queue using `queue.process`? This would allow to mark a job as failed when a worker processing the job crashed without having had time to call `done(err)`. 

This could be useful as an extra safety net, when it's certain certain jobs are done within a given period of time

**Comment by behrad** [comment] 2015-03-30 09:13
duplicate of https://github.com/Automattic/kue/issues/544

**Closed by behrad** 2015-03-30 09:13 UTC
Labels: Duplicate, Feature
