### ISSUE TITLE
Web Interface Doesn't work properly (redirects to /active without hostname)

### ISSUE THREAD

**Issue by TylerBrock** [Automattic/kue#715] opened 2015-09-22 22:29 UTC
Hey everyone, I've tried starting the web interface as described in the documentation:

```js
var kue = require('kue');
kue.createQueue();
kue.app.listen(3000);
```

When the app runs and I visit "http://localhost:3000" in a browser it redirects to "/active" without the scheme and hostname portion of the URL. Manually entering back the scheme and hostname allows the /active page to render but without any assets or javascript.

I've tried loading the page in Chrome 45 and Safari (latest version) with the same result.

**Comment by behrad** [comment] 2015-09-23 05:06
which kue version @TylerBrock ?

**Comment by TylerBrock** [comment] 2015-09-23 05:38
0.9.5

**Comment by m2sh** [comment] 2015-09-23 05:45
I have the same problem, but when using [kue ui](https://github.com/StreetHub/kue-ui) there is no problem & both UIs works fine.

**Comment by behrad** [comment] 2015-09-23 05:50
This should be caused by the latest commits to support for embedding kue inside other express apps. please check https://github.com/Automattic/kue/commit/447f525c2612369d42857cd39687cbdfa64e880c

**Comment by TylerBrock** [comment] 2015-09-23 17:53
That fixes it but for the simple use case I outline above (the hostname is now included) but it still doesn't respect the outer context with regards to where it's mounted.

For example I'm mounting the application at "/queue" but visiting `localhost:3000/queue` redirects to `localhost:3000/active` instead of `localhost:3000/queue/active`

**Comment by TylerBrock** [comment] 2015-09-23 18:04
It seems I can work around it by specifying a path when mounting kue in the sub-app by specifying `app.use('/queue', app.kue)` but it prevents it from being mounted somewhere besides `/queue` in the parent application.

Thanks for maintaining this btw. Great stuff.

**Comment by behrad** [comment] 2015-09-23 18:45
Any one can provide a more general PR to handle all scenarios?

**Comment by azimgd** [comment] 2015-09-25 07:49
Hi, 
i was able to fix it. please take a look to PR.

**Comment by behrad** [comment] 2015-09-25 08:06
does this work for both express 3 and express 4 !?

**Comment by azimgd** [comment] 2015-09-25 08:12
I've tried with express 4 only, let me recheck with express 3 as well.

**Comment by azimgd** [comment] 2015-09-25 08:16
Redirection from subdomain is failing.

**Comment by behrad** [comment] 2015-09-25 08:23
I believe all two cases for both express versions (4 scenarios) should be considered to be fixed.
Thank you @azimgd

**Comment by azimgd** [comment] 2015-09-25 08:48
This fix tested both on express v3 and v4, redirection on root and subfolder is working now.

**Comment by behrad** [comment] 2015-09-25 08:57
nice @azimgd 
Are you using kue-ui? Can you test that if does work too?

**Comment by azimgd** [comment] 2015-09-25 09:23
I had some troubles with running kue-ui itself, but setting it up as described in documentation and accessing kue interface via /api produces correct redirections.

hostname.dev/subfolder/api/ -> hostname.dev/subfolder/api/active
hostname.dev:3000/api/ -> hostname.dev:3000/api/active

**Comment by azimgd** [comment] 2015-09-26 07:23
Any updates regarding on this @behrad ?

**Comment by behrad** [comment] 2015-09-26 08:19
i will test and merge this in a few days @azimgd

**Comment by azimgd** [comment] 2015-10-01 06:06
Any updates on this @behrad ?

**Comment by behrad** [comment] 2015-10-01 06:31
tested and merged

**Closed by behrad** 2015-10-01 06:31 UTC
Labels: Bug, needs pull request

**Comment by maxcnunes** [comment] 2015-10-06 13:14
Could you please publish a new version including this fix? Thanks.

**Comment by behrad** [comment] 2015-10-06 19:34
Done!
