### ISSUE TITLE
calling done() in a setTimeout function make another job to change state in inactive mode or stucks in active mode 

### ISSUE THREAD

**Issue by behroozshafiabadi** [Automattic/kue#1057] opened 2017-05-08 06:26 UTC
seems that happen! could you explain me why ?
tnx to you behrad

**Comment by ejoebstl** [comment] 2017-05-16 09:35
Could you add some minimal code to reproduce to this issue?

I think I'm having a similar problem on a production system, but I have not managed to reproduce locally.

**Comment by TheGrandmother** [comment] 2017-05-16 13:17
Are you sure that the correct reference is being captured by the callback?
Some code would be greatly appreciated.

**Comment by behrad** [comment] 2017-05-18 11:14
I can't figure your issue out @behroozshafiabadi 
Can you please send us a code snip?

**Comment by TheGrandmother** [comment] 2017-05-26 10:49
I think I'm actually stuck in the same situation.
Not sure if it is due to `setTimeout` but I'm doing a lot of asynchronous stuff.

Although I'm a bit unsure why this would happen.

**Comment by TheGrandmother** [comment] 2017-05-26 11:55
I think i might have some more information on this.

It appears that  `getJob` starts to behave oddly.
The `client.blpop` call on https://github.com/Automattic/kue/blob/master/lib/queue/worker.js#L271 starts returning `false` and the callback does not fire. Therefore no error gets reported, the function exits normally with no job picked up and the job remains stuck.

Why this is i do not know :/

**Comment by TheGrandmother** [comment] 2017-05-29 08:32
I think i have made some more progress with this issue.

I think the problem might be. Apparently the problem is that the lock aquired by `client.blpop` never gets released.I think the isue is that when a worker dies it does not get shutdown properly.
In my configuration the workers are running on different processes than the "master" queue.

@behrad
Is there a way to shut down a single worker remotely? The problem is that AFAIK the `queue.shutdown` function will kill all the workers. I need the option to shutdown a single worker locally. I need to be able to do graceful shutdown for a specific worker.

**Comment by behrad** [comment] 2017-06-01 08:30
You can use redis cli to monitor your BLPOP connection and make sure if it is released or not.
Looks abit strange to me

**Comment by TheGrandmother** [comment] 2017-06-01 09:17
@behrad 
I found the issue and it was a user problem in my case.
I didn't use the `shutdown` method properly and what happened was that the `BLPOP` did not release the lock. When this happens the callback did not fire and all remaining active jobs just hung around forever.

**Comment by behrad** [comment] 2017-06-02 06:07
closing for now, don't mind to reopen.

**Closed by behrad** 2017-06-02 06:07 UTC
